openapi: 3.0.3
info:
  title: Docupilot accounts APIs ai saml API
  version: '1.0'
  description: Docupilot accounts APIs
  termsOfService: https://docupilot.app/terms-and-conditions/
  contact:
    name: Team Docupilot
    email: support@docupilot.app
tags:
- name: saml
paths:
  /accounts/saml/:
    get:
      operationId: list_saml_providers
      summary: Get list of SAML providers
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      tags:
      - saml
      security:
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SAMLProviderList'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
    post:
      operationId: create_saml_provider
      summary: Create SAML provider
      tags:
      - saml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SAMLProviderCreate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SAMLProviderCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SAMLProviderCreate'
        required: true
      security:
      - SessionAuthentication: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SAMLProviderCreate'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
  /accounts/saml/{id}/:
    get:
      operationId: retrieve_saml_provider
      summary: Retrieve SAML provider
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this social application.
        required: true
      tags:
      - saml
      security:
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SAMLProviderRetrieve'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
    put:
      operationId: update_saml_provider
      summary: Update SAML provider
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this social application.
        required: true
      tags:
      - saml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SAMLProviderUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SAMLProviderUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SAMLProviderUpdate'
        required: true
      security:
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SAMLProviderUpdate'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
    patch:
      operationId: saml_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this social application.
        required: true
      tags:
      - saml
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedSAMLProviderUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedSAMLProviderUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedSAMLProviderUpdate'
      security:
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SAMLProviderUpdate'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
    delete:
      operationId: delete_saml_provider
      summary: Delete SAML provider
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this social application.
        required: true
      tags:
      - saml
      security:
      - SessionAuthentication: []
      responses:
        '204':
          description: No response body
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
  /accounts/saml/{id}/toggle_active/:
    post:
      operationId: toggle_saml_provider
      summary: Toggle SAML provider active status
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this social application.
        required: true
      tags:
      - saml
      security:
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SAMLProviderRetrieve'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
components:
  schemas:
    UnauthenticatedError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    SAMLProviderList:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 40
        type:
          type: string
          readOnly: true
        is_setup_complete:
          type: boolean
          readOnly: true
        active:
          type: boolean
      required:
      - active
      - id
      - is_setup_complete
      - name
      - type
    ValidationError:
      type: object
      properties:
        errors:
          type: object
          additionalProperties: {}
        non_field_errors:
          type: array
          items:
            type: string
      required:
      - errors
      - non_field_errors
    ForbiddenError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    PatchedSAMLProviderUpdate:
      type: object
      properties:
        metadata_url:
          type: string
          format: uri
          description: Metadata URL of the Identity Provider
        name:
          type: string
          description: Name of the SAML provider
    SAMLProviderUpdate:
      type: object
      properties:
        metadata_url:
          type: string
          format: uri
          description: Metadata URL of the Identity Provider
        name:
          type: string
          description: Name of the SAML provider
      required:
      - metadata_url
      - name
    SAMLProviderRetrieve:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 40
        client_id:
          type: string
          description: App ID, or consumer key
          maxLength: 191
        entity_url:
          type: string
          format: uri
          readOnly: true
        acs_url:
          type: string
          format: uri
          readOnly: true
        metadata_url:
          type: string
          format: uri
          readOnly: true
        type:
          type: string
          readOnly: true
        active:
          type: boolean
      required:
      - acs_url
      - active
      - client_id
      - entity_url
      - id
      - metadata_url
      - name
      - type
    NotFoundError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    SAMLProviderCreate:
      type: object
      properties:
        name:
          type: string
          maxLength: 40
        type:
          enum:
          - microsoft
          - okta
          type: string
      required:
      - name
      - type
  securitySchemes:
    OAuthAuthentication:
      type: http
      scheme: bearer
      description: OAuth2 Bearer Token Authentication
    SessionAuthentication:
      type: apiKey
      in: cookie
      name: sessionid
      description: browser based login takes care of this
externalDocs:
  description: Help docs on how to use API
  url: https://help.docupilot.app/developers/api-overview
