openapi: 3.0.3
info:
  title: Docupilot accounts APIs ai domain API
  version: '1.0'
  description: Docupilot accounts APIs
  termsOfService: https://docupilot.app/terms-and-conditions/
  contact:
    name: Team Docupilot
    email: support@docupilot.app
tags:
- name: domain
paths:
  /accounts/domain/:
    get:
      operationId: list_domains
      summary: List domains
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      tags:
      - domain
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
    post:
      operationId: create_domain
      summary: Create domain
      tags:
      - domain
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Domain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Domain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Domain'
        required: true
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
  /accounts/domain/{id}/:
    delete:
      operationId: destroy_domain
      summary: Destroy domain
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this domain.
        required: true
      tags:
      - domain
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      responses:
        '204':
          description: No response body
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
  /accounts/domain/{id}/toggle_lock/:
    patch:
      operationId: toggle_domain_lock
      summary: Toggle domain lock
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this domain.
        required: true
      tags:
      - domain
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
  /accounts/domain/{id}/verify/:
    patch:
      operationId: verify_domain
      summary: verify domain
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this domain.
        required: true
      tags:
      - domain
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
          description: ''
  /dashboard/api/v2/domain/{id}/:
    get:
      operationId: get_domain
      summary: Get one domain
      parameters:
      - in: header
        name: X-Workspace
        schema:
          type: string
        description: Workspace unique_key
        required: true
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this domain.
        required: true
      tags:
      - domain
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain_2'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError_2'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError_2'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError_2'
          description: ''
  /dashboard/api/v2/domain/{id}/verify/:
    patch:
      operationId: verify_domain
      summary: verify domain
      parameters:
      - in: header
        name: X-Workspace
        schema:
          type: string
        description: Workspace unique_key
        required: true
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this domain.
        required: true
      tags:
      - domain
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedDomain'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedDomain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedDomain'
      security:
      - OAuthAuthentication: []
      - SessionAuthentication: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainVerify'
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError_2'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError_2'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError_2'
          description: ''
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError_2'
          description: ''
components:
  schemas:
    UnauthenticatedError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    DomainVerify:
      type: object
      properties:
        success:
          type: array
          items:
            enum:
            - txt_record
            - spf_record
            type: string
        failures:
          $ref: '#/components/schemas/DomainFailure'
      required:
      - failures
      - success
      description: ''
    ValidationError:
      type: object
      properties:
        errors:
          type: object
          additionalProperties: {}
        non_field_errors:
          type: array
          items:
            type: string
      required:
      - errors
      - non_field_errors
    Domain:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        domain_name:
          type: string
          maxLength: 70
        txt_record:
          type: string
          readOnly: true
        is_txt_verified:
          type: boolean
          readOnly: true
        is_locked:
          type: boolean
          readOnly: true
        verification_expired_at:
          type: string
          format: date-time
          readOnly: true
          nullable: true
      required:
      - domain_name
      - id
      - is_locked
      - is_txt_verified
      - txt_record
      - verification_expired_at
    ForbiddenError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    DomainFailure:
      type: object
      properties:
        spf_record:
          type: string
        txt_record:
          type: string
      required:
      - spf_record
      - txt_record
      description: ''
    ValidationError_2:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        non_field_errors:
          type: array
          items:
            type: string
      required:
      - errors
      - non_field_errors
      description: ''
    NotFoundError_2:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
      description: ''
    PatchedDomain:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        domain_name:
          type: string
          maxLength: 255
        txt_record:
          type: string
          maxLength: 60
        is_txt_verified:
          type: boolean
        is_spf_verified:
          type: boolean
        spf_record:
          type: string
          readOnly: true
      description: ''
    ForbiddenError_2:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
      description: ''
    NotFoundError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
    Domain_2:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        domain_name:
          type: string
          maxLength: 255
        txt_record:
          type: string
          maxLength: 60
        is_txt_verified:
          type: boolean
        is_spf_verified:
          type: boolean
        spf_record:
          type: string
          readOnly: true
      required:
      - domain_name
      - id
      - spf_record
      - txt_record
      description: ''
    UnauthenticatedError_2:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
      description: ''
  securitySchemes:
    OAuthAuthentication:
      type: http
      scheme: bearer
      description: OAuth2 Bearer Token Authentication
    SessionAuthentication:
      type: apiKey
      in: cookie
      name: sessionid
      description: browser based login takes care of this
externalDocs:
  description: Help docs on how to use API
  url: https://help.docupilot.app/developers/api-overview
