openapi: 3.2.0
info:
  title: Docupilot V2 Personalization API
  version: '3.0'
  description: Docupilot V2 APIs
  termsOfService: https://docupilot.app/terms-and-conditions/
  contact:
    name: Team Docupilot
    email: support@docupilot.app
tags:
- name: Personalization
paths:
  /dashboard/api/v2/personalization/:
    get:
      operationId: get_user_personalization
      parameters:
      - in: header
        name: X-Workspace
        schema:
          type: string
        description: Workspace unique_key
        required: true
      tags:
      - Personalization
      security:
      - SessionAuthentication: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPersonalization'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenError'
          description: ''
      summary: Get user personalization
      x-summary-source: derived
    post:
      operationId: update_user_personalization
      parameters:
      - in: header
        name: X-Workspace
        schema:
          type: string
        description: Workspace unique_key
        required: true
      tags:
      - Personalization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPersonalization'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserPersonalization'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserPersonalization'
      security:
      - SessionAuthentication: []
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: ''
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthenticatedError'
          description: ''
      summary: Update user personalization
      x-summary-source: derived
components:
  schemas:
    UnauthenticatedError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
      description: ''
    ForbiddenError:
      type: object
      properties:
        detail:
          type: string
      required:
      - detail
      description: ''
    UserPersonalizationListViewTemplate:
      type: object
      properties:
        type:
          enum:
          - card
          - template
          type: string
      required:
      - type
      description: ''
    ValidationError:
      type: object
      properties:
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        non_field_errors:
          type: array
          items:
            type: string
      required:
      - errors
      - non_field_errors
      description: ''
    UserPersonalization:
      type: object
      properties:
        ui_version:
          enum:
          - 1
          - 2
          type: integer
        list_view:templates:
          $ref: '#/components/schemas/UserPersonalizationListViewTemplate'
        tp:freshchat:restoreId:
          type: string
          format: uuid
      description: ''
  securitySchemes:
    OAuthAuthentication:
      type: http
      scheme: bearer
      description: OAuth2 Bearer Token Authentication
    SessionAuthentication:
      type: apiKey
      in: cookie
      name: sessionid
      description: browser based login takes care of this
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Basic"
externalDocs:
  description: Help docs on how to use API
  url: https://help.docupilot.app/developers/api-overview
